FROM golang:1.22-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/messaging ./services/messaging

FROM alpine:3.19
RUN apk --no-cache add ca-certificates
COPY --from=builder /bin/messaging /bin/messaging

EXPOSE 50052
CMD ["/bin/messaging"]
